### ISSUE TITLE
python-goloslib fork

### ISSUE THREAD

**Issue by cryptomental** [xeroc/piston-lib#13]
Hi @xeroc,

I recently wrote a short post at Golos on how to use their forked versions of python-graphenelib, python-steemlib and conservatorio (piston). While I think that graphenelib could stay as-is with a minor update, python-steemlib could be renamed into python-goloslib and their version of piston as they currently have : conservatorio to make it installable with plain pip.

At first I thought of making a generic 'socialchainlib' but came to the conclusion that in the future Golos chain may contain different features than Steem and it might be a considerable effort to maintain both. Generic features will be kept in python-graphenelib anyway.

I (and probably Golos team) could rename the two forks, leaving you as the main author and push it to Python Package Index The question is if you have any objections and agree to do so.

Hope to hear from you,
Przemek (@cryptomental)

**Comment by xeroc** [comment]
you could make python-goloslib extend python-steemlib and simply add the chainid for golos.
Or .. we simply extend python-steemlib and add golos' chain id there there ..

Piston should be able to obtain the chain id automatically through the API and the underlying API-wrapper (python-steem/python-golo) to the backend node and just thus work with golos out of the box ..

**Comment by cryptomental** [comment]
Thanks. Sounds like a reasonable approach. I initially also thought about adding the golos' chain id to python-steemlib but they may also need Russian documentation including the code examples, therefore 'python-goloslib extend python-steemlib' will be a way to go as the Russian docs can go there. 

You are right, Piston should automatically switch to the backend node via the middleman python-[steem/golos]lib but currently Piston has a few hardcoded references to steem there like https://github.com/xeroc/piston/blob/master/piston/steem.py#L880 , therefore a wrapper/fork may be also needed.

**Comment by cryptomental** [comment]
I am closing this question as resolved then. This will hopefully land in GolosChain this/next week. Thanks!
