### ISSUE TITLE
Cannot get balance

### ISSUE THREAD

**Issue by clayop** [xeroc/piston-lib#15]
steem.get_balances("clayop")

{'balance': <steem.amount.Amount object at 0x7f0a0f25ef98>, 'vesting_shares': <steem.amount.Amount object at 0x7f0a0f2704a8>, 'sbd_balance': <steem.amount.Amount object at 0x7f0a0f2705c0>, 'savings_balance': <steem.amount.Amount object at 0x7f0a0f2705f8>, 'savings_sbd_balance': <steem.amount.Amount object at 0x7f0a0f270668>, 'vesting_shares_steem': <steem.amount.Amount object at 0x7f0a0f2706d8>}

**Comment by Netherdrake** [comment]
`Amount` is a new data structure to deal with STEEM currencies accurately.

You can resolve it by calling `amount,asset` properties on the Amount object, for example, if `str(Amount)` is `100.001 STEEM`, then `Amount().amount` will be `100.001` and `Amount().asset` will be `STEEM`.

Try it:
```
steem.get_balances("clayop")['balance'].amount
```

**Comment by clayop** [comment]
Thanks! (is .amount float or str?)

**Comment by xeroc** [comment]
.amount is a `float`
