### ISSUE TITLE
How to get blog permlinks?

### ISSUE THREAD

**Issue by Netherdrake** [xeroc/piston-lib#18]
I can't seem to be able to get blogs anymore.

For example, all of these will blow up:
```
s = Steem()
blog = [Post(x['identifier']) for x in s.get_blog(account_name)]
pprint([x['identifier'] for x in s.get_blog(account_name)])

blog = Account(account_name).get_blog()[:20]
blog = Blog(account_name)[:20]
blog2 = [Post(x['identifier']) for x in blog]
```

Error:
```
  File "/home/user/GitHub/python-steem/steem/post.py", line 133, in __getitem__
    return super(Post, self).__getitem__(key)
KeyError: 'identifier'
```

The only workaround I found so far is:
```
    blog = []
    for x in s.get_blog(account_name):
        x.refresh()
        blog.append(x)
```

Am I missing something here?

**Comment by Netherdrake** [comment]
I have implemented Blog as an iterator. This allows for very easy to use and powerful API. 

User can request as many blog posts as they like, and it will return them in a LIFO (newest posts first) order. The iterator is lazy, and it will only request things from RPC when needed (batching of 1000 historic items).

![](https://i.gyazo.com/764cc8d417a74b1ad46bea45770075e7.png)

I am not 100% happy with the code beauty, especially [this](https://github.com/xeroc/python-steem/blob/develop/steem/blog.py#L23-L36) part, but the implementation is well tested and it appears to be working well.

Commit: https://github.com/xeroc/python-steem/commit/55027b783442df5720bf705e7650bff2a584884e

**Comment by xeroc** [comment]
`identifier` was only an attribute, not a key.. i fixed it
