### ISSUE TITLE
Cannot import SimpleCache

### ISSUE THREAD

**Issue by clayop** [xeroc/piston-lib#22]
```
>>> from steem.account import Account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/steem/account.py", line 11, in <module>
    from .converter import Converter
  File "/usr/local/lib/python3.5/dist-packages/steem/converter.py", line 6, in <module>
    from .utils import SimpleCache, simple_cache
ImportError: cannot import name 'SimpleCache'
```

I tried manually upgrade `werkzeug` but didn't work too.

**Comment by xeroc** [comment]
@Netherdrake thoughts on this?
Can we implement our own simple cache? I don't like to require `werkzeug` as dependency

**Comment by Netherdrake** [comment]
I agree, `werkzeug` is an overkill, especially since we've removed all the caches elsewhere. I think we could just drop caching from `Converter` as well, and re-consider adding some simpler implementation if deemed necessary in the future.

**Comment by clayop** [comment]
Cool info. Waiting for your update and I will publish my feed script after that.

**Comment by Netherdrake** [comment]
I've removed SimpleCache https://github.com/xeroc/python-steem/commit/00e33413e3633f34284bbe96dbbe4693fcdf72b0
