### ISSUE TITLE
Voting Power refresh

### ISSUE THREAD

**Issue by ArtGenesis** [xeroc/piston-lib#23]
I tried get my Voting Power and always get same value, only when i have voted, Voting Power is changes, for example even if i get 80%, after vote i can get 95%, if VP full recovering

```
from steem.account import Account
account = Account("myAcc")
acc_vp = account.voting_power()
print(acc_vp)
```

On steemd, Voting Power always change when i open page
So to get a Voting Power in real-time(like steemd) , i do something like:

```
from steem.account import Account
import datetime, time

account = Account("myAcc")
acc_vp = account.voting_power()
votime = account.get_account_votes()[-1]['time']  #get last vote time
vot = datetime.datetime.strptime(votime, '%Y-%m-%dT%H:%M:%S')
vot = time.mktime(vot.timetuple())
tnow = datetime.datetime.utcnow().timestamp()
 #not for sure about 0.0139, but result like on steemd (in most cases)
dif = (((tnow-vot)/60)* 0.0139)  + acc_vp  
if dif >= 100:
    dif = 100
    print(dif)
else:
    print(dif)
```
Maybe i do it something wrong, and there are easier method. Thanks!

**Comment by Netherdrake** [comment]
To refresh the account info, just call `account.refresh()`.

```
from steem.account import Account
account = Account("myAcc")
print(account['voting_power'])

# some time later
account.refresh()
print(account['voting_power'])
```

**Comment by ArtGenesis** [comment]
Thanks, @Netherdrake, but for me account.refresh() not help in this case, returned same value VP :(

**Comment by Netherdrake** [comment]
I've checked my voting power, upvoted a few posts on steemit and immediately checked again. It seems to be working for me.

```
In [8]: a.refresh()

In [9]: a['voting_power']
Out[9]: 8982

In [10]: a.refresh()

In [11]: a['voting_power']
Out[11]: 8855

In [12]: 
```

**Comment by ArtGenesis** [comment]
When i upvoted and then checked VP working for me too(even without refresh), but when i not upvoted, VP recovering, seem like 0.01% in minute, and i would like check real VP

**Comment by Netherdrake** [comment]
I apologize for not reading your original post carefully. I have tested the case, and yes, you're right.

It seems like `steemd` only updates the `voting_power` with each vote.

Your code does pretty much what you want to do, and if I were to implement it, I'd likely do the same.

**Comment by ArtGenesis** [comment]
Thanks for consultation Netherdrake!
