### ISSUE TITLE
Regression: Steem() can no longer connect to custom node

### ISSUE THREAD

**Issue by Netherdrake** [xeroc/piston-lib#24]
```
In [15]: s = Steem(node='wss://this.piston.rocks')

In [16]: s
Out[16]: <steem.steem.Steem object at 0x7ff69c06c780>

In [17]: s.rpc.url
Out[17]: 'wss://steemit.com/wspa'

In [18]: s = Steem(node=['wss://this.piston.rocks'])

In [19]: s.rpc.url
Out[19]: 'wss://steemit.com/wspa'
```

A quick hack workaround:
![](https://i.gyazo.com/b39f9a71e03e8bb2f581568f7476354f.png)

On a slightly ranty note, I am not a fan of having both instance and class variables and the spaghetti of state and mutation thereof interleaved all over the place, as it makes it really hard to understand what is going on.

The problem becomes more pronounced in larger apps (especially if multithreaded), where different parts of code might need Steem in a different configuration (ie. different node url, or broadcast/nobroadcast state). Currently its impossible to reason about what will happen in production.

Perhaps it would be simpler to remove class variables alltogether, and in the `Steem.__init__`, lookup the piston config for settings that are not provided by the user. Furthermore, by always creating a Steem instance fresh, and containing state and state mutations to that instance only, users would have some level of certainty over what the expected state should be. Yes, this would add a bit of resource overhead, but I think its worth it.

**Comment by xeroc** [comment]
The reason for having those class variables was that I would like multiple classes to share a single RPC connection. That way, a code like this:

```python
from steem.block import Block
from steem.blockchain import Blockchain

Block()
BlockChain()
```

Share the same RPC connection and don't open up new ones.
Same holds true for the Wallet class.

However, I am also not very happy with the confusion that is added to the code this way.
How would you propose to get the best parts of both worlds, simple code and a singelton RPC interface?

**Comment by Netherdrake** [comment]
All classes already support `steem_instance` parameter, for passing user defined instance.

If we want to share a single connection between all classes by default, perhaps a namespace bound variable can be created in `steem` which is only initialized once (the first time its called) trough `default_steem_instance()`. (this instance is based on defaults in piston config).

Example impl in `steem.py`:
```python
_global_steem_instance = None

def default_steem_instance():
    if not _global_steem_instance:
        _global_steem_instance = Steem(**piston_config)
    return _global_steem_instance
```

Then, classes like `Block` and `Blockchain` can just do:

```python
from steem import default_steem_instance

class Block():
    def __init__(..., steem_instance=None):
        self.steem = steem_instance or default_steem_instance()
```

Furthermore, in the case where one class uses the other, it could just pass on its own instance by default, ensuring that user defined instances propagate properly:

Example for `Blockchain` method: 
```python
    def get_current_block(self):
        """ This call returns the current block
        """
        return Block(self.get_current_block_num(), steem_instance=self.steem)
```

This would allow users to:
1.) Override the default instance for *all classes* by modifying/overloading underlying default in `steem`.
2.) Override the default instance for *single class* by providing their steem instance via `steem_instance=` argument.
3.) Ability to create clean and easy to reason with `Steem()` instances.

The Steem() class is the most fundamental part of python-steem, and by isolating state mutations to its instances it would make it simpler, less bug prone and re-usable.

**Comment by xeroc** [comment]
The `default_steem_instance` could still see if there already is a open connection and reuse it as a default behavior?

**Comment by Netherdrake** [comment]
Yes.

`default_steem_instance()` initializes the global steem instance, or returns the reference to said instance if it already exists.

As far as my understanding goes, python is pass by reference, and with the above pattern, for most users, only a single instance/connection would exist (default behavior). 
For users who want to define their own instance and pass it to classes, there would be 2 connections at most, the default one and user defined one. So the worst case overhead is really minimal.

*In SteemSports example, there would be up to 3 at a time. Creating new connections is preferable to mutating shared state and risking unforeseeable bugs, such as the incident with paying for real in simulation mode.*

In any case, the user should have the flexibility to decide for what is best for their application.

**Comment by Netherdrake** [comment]
I have implemented the above proposal, see branch `24` https://github.com/xeroc/python-steem/tree/24

**Comment by Netherdrake** [comment]
Here are two examples of overloading the default Steem instance:

1.) Override the Steem instance for individual class (this instance only).
![](https://i.gyazo.com/85944e2642ba31af02d25474a4d0a5f4.png)

2.) Override the default Steem instance
![](https://i.gyazo.com/6ab526209750a568dc31f900c63e3b70.png)
The nice thing here is that instances initialized before calling `set_shared_steem_instance` don't have their rug pulled  from beneath them. If user wishes to use custom default instance from get-go, they just call `set_shared_steem_instance()` once at the beginning of their program.

**Comment by sneak** [comment]
Soon we're going to stop using websockets entirely in favor of plain ol' HTTP(s) requests, so I imagine this will be pretty unimportant, although you still might want to support different endpoint URLs (but reusing a connection won't be a thing).

**Comment by Netherdrake** [comment]
hi @sneak, pleasure to see you lurking in here.

I actually kind of like WebSockets, since they are a lot more efficient than HTTP1.1 (there is no setup/teardown cost).

Can you tell us a little bit more about what exactly will change (just the transport or API as well)?
Will the new API be served by steemd?
Will it support HTTP2?
Is this feature 'planned' or has it already been developed? ETA release?

**Comment by xeroc** [comment]
@sneak, the problem described here is actually independent of how the connection is made. There is some RPC connection and we would like it to share (if possible) with different classes. If websocket goes away, i would like to only chance the underlying rpc code and not the code that builds on top of it.

@Netherdrake Thanks for the pull request, but I think we can do something easier.
Your use-case basically breaks because of these lines:
https://github.com/xeroc/python-steem/blob/master/steem/steem.py#L142-L149
(which have been a stupid but quick implementation)

Anyway, I would like to fix this issue by simply distinguishing three cases:

1. There is a `Steem.rpc` defined already and no new url is provided: We use `self.rpc = Steem.rpc`
2. There is a `Steem.rpc` and a different url is provided, we set a new `self.rpc` and keep `Steen.prc` untouched
3, `Steem.rpc` is empty and no url is provided, we connect `Steem.rpc` with the default connection and refer to it with `self.rpc`

That would make the patch pretty easy and would keep most of the code as it is.

**Comment by Netherdrake** [comment]
@xeroc if I understand correctly, this would remove all class variables but `Steem.rpc`. 

I think it could work, but please don't forget about fallback nodes (ie. `Steem(node=['node1', 'node2', 'node3']`).
*Without fallback nodes, services like SteemData and SteemSports would break every time the main node goes down.*

**Comment by xeroc** [comment]
The reason I have setup `wallet` as a class variable was to prevent the app from asking the user for an unlock password multiple times if he just forgot to hand over the steem intance.
I still see some advantages in using class variables and would like to propose a fork for testing today @Netherdrake

**Comment by xeroc** [comment]
Good job on this pull request .. I like it so much that I am now also using it in pybitshares.
Also, I thin the `instance.py` could be used to define a *new default* if people don't want to use the explicit `steem_instance` all the time ..

**Comment by Netherdrake** [comment]
@xeroc yes, thats what `instance.set_shared_steem_instance()` does. The user can just call it at beginning of their script, and thus effectively change the default instance to their own.

**Comment by xeroc** [comment]
lol .. didn't know that you had that added already ... awesome job!
