### ISSUE TITLE
0.4.3 doesn't work?

### ISSUE THREAD

**Issue by oflyhigh** [xeroc/piston-lib#25]
# Manual installation

Got following error
  File "build/bdist.linux-armv7l/egg/steem/steem.py", line 632
    **s,
       ^
SyntaxError: invalid syntax

# Installed with pip3 
Run piston
~/.local/bin $ ./piston
Traceback (most recent call last):
  File "./piston", line 7, in <module>
    from piston.__main__ import main
  File "/home/pi/.local/lib/python3.4/site-packages/piston/__main__.py", line 11, in <module>
    from steem.storage import configStorage as config
  File "/home/pi/.local/lib/python3.4/site-packages/steem/__init__.py", line 1, in <module>
    from .steem import Steem
  File "/home/pi/.local/lib/python3.4/site-packages/steem/steem.py", line 632
    **s,
       ^
SyntaxError: invalid syntax

What's wrong?

**Comment by xeroc** [comment]
weird .. it is not invalid syntax for python 3.5.2 in linux .. I will see what caused this for you.
The relevant code isn't as I would like it to be anyways :)

**Comment by Netherdrake** [comment]
He is using an old 3.4 version.

@oflyhigh I'd recommend against using an OS version of Python. By using virtualenv or a distribution like [Anaconda](https://www.continuum.io/downloads) you can separate OS space and user space and ensure that everything *just works* without the ability to break OS stuff.

**Comment by Netherdrake** [comment]
The code is a bit weird, but not technically invalid:

```
In [4]: foo = {'1': 1}

In [5]: def bar(*args, **kwargs):
   ...:     print(kwargs)
   ...:     

In [6]: bar(**foo, baz=2)
{'baz': 2, '1': 1}
```

**Comment by oflyhigh** [comment]
I use Python 3.4.2, it doesn't work with above example, I'll try to install Python 3.5.
And I think it should be better to be compatible with the old version:)
Thank you all.

**Comment by Netherdrake** [comment]
Try Anaconda. I could not praise it enough.

**Comment by oflyhigh** [comment]
Thank you, Python3.5 works OK for me.

BTW:
The follow code style worked with Python 3.4.2
So， could you change the code in steem.py in this way?

```
foo = {'1': 1}

def bar(*args, **kwargs):
        print(kwargs)

bar(baz=2, **foo)
```

**Comment by xeroc** [comment]
I updated the code which hopefully resolves the issue .. would you please try the `develop` branch?

// edit: Thanks for the code snippet!
