### ISSUE TITLE
AssertionError: assert other["asset"] == self["asset"] in amount.py

### ISSUE THREAD

**Issue by ArtGenesis** [xeroc/piston-lib#33]
Tryed get "pending_payout_value" from Post, heretofore worked fine, today get AssertionError in amount.py

```Python
if isinstance(other, Amount):
            assert other["asset"] == self["asset"]
```
other["asset"] is STEEM
self["asset"]  is SBD

```Python
site-packages\steem\amount.py", line 59, in __add__
    assert other["asset"] == self["asset"]
```

**Comment by xeroc** [comment]
Yhea .. this is something related to steem 0.17 release .. i don't know what exactly .. but i fixed it in `develop` already.. will be part of the next release

**Comment by ArtGenesis** [comment]
Good, and trouble now, when tried vote, in post.py 
myacc.get_content(ident).vote(VOTE_WEIGHT, voter = ACCOUNT)

```Python
steem\post.py", line 233, in vote
    if getattr(self, "mode") == "archived":
steem\post.py", line 152, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'Post' object has no attribute 'mode'
```

now i just commented part of code:

```Python
#if getattr(self, "mode") == "archived":
     #raise VotingInvalidOnArchivedPost
```

**Comment by Netherdrake** [comment]
Mode has been deprecated. I'm using `net_rshares`, which will be reset to 0 after payout. Any better ideas welcome.

**Comment by Netherdrake** [comment]
Condenser uses `cashout_time`:
https://github.com/steemit/condenser/pull/1260/commits/417bf5e1eeb1770e2ea24ace1989312821006a21

**Comment by pmartynov** [comment]
What is the date of the next release?

**Comment by xeroc** [comment]
@pmartynov 
Just today! :D  
https://github.com/xeroc/piston-lib/releases/tag/0.5.1
