### ISSUE TITLE
Comment Stream returns old comments

### ISSUE THREAD

**Issue by marvin-bitterlich** [xeroc/piston-lib#50]
It seems to me that streeming of comments finds old posts, often multiple days old…

It may be that the stream matches resteems but I could not verify this. Is there a way to filter out resteems?

**Comment by Netherdrake** [comment]
you mean `steem.stream_comments()`?

If its streaming old content, while asked to stream head, it means that the node its connected to is lagging behind.

**Comment by marvin-bitterlich** [comment]
That is really weird then. Because I got posts from 2 days ago using this method… That is lagging way behind!

**Comment by Netherdrake** [comment]
what is the output of `piston config` in cli?

**Comment by marvin-bitterlich** [comment]
```
 > piston config
+-----+-------+
| Key | Value |
+-----+-------+
+-----+-------+

```

Only used the lib so far, so this is a fresh install…

**Comment by Netherdrake** [comment]
try `piston set node wss://steemd.steemit.com`

**Comment by marvin-bitterlich** [comment]
I'll report back with how that works!

**Comment by marvin-bitterlich** [comment]
Still the same thing: I got this post https://steemit.com/fusion360/@lazzelazer/intro-inventor-3d-specialist-gold-prospector-among-other-things-checking-in from yesterday. 

Are you sure resteems are filtered out?

**Comment by ArtGenesis** [comment]
It's because posts, that was edited, add to new block

last_update	2017-06-04 17:35:48
created	2017-06-03 17:18:33

```python
from steem.post import Post
post = Post("@lazzelazer/intro-inventor-3d-specialist-gold-prospector-among-other-things-checking-in")
print(post["created"])
print(post["last_update"])
```

**Comment by Netherdrake** [comment]
oh, ok.
