### ISSUE TITLE
Get Open Orders

### ISSUE THREAD

**Issue by JasonMcz** [xeroc/piston-lib#6]
I saw under the exchange function 
get_open_orders had pass for now.

Are we gonna implement the real one? 
The steemit/market seems to have get_open_orders with its wss.

**Comment by JasonMcz** [comment]
`def returnOpenOrders(self, currencyPair="all"):
        pass`

**Comment by xeroc** [comment]
That one and the `getBalance` are being worked on.

**Comment by JasonMcz** [comment]
Sounds good. Is there an API calls liquidity point? or do you know any?

**Comment by JasonMcz** [comment]
@xeroc you think you gonna add one person's trading history?
is it possible to get that data?

**Comment by xeroc** [comment]
https://github.com/xeroc/python-steemlib/commit/de1db3cbb12a83569a072c03499d36fced053851

a call for account history will come aswell .. give me some time
