### ISSUE TITLE
[Feature] Automatic fall-back to a backup node

### ISSUE THREAD

**Issue by Netherdrake** [xeroc/piston-lib#9]
Example:

```
steem = Steem(node="ws://127.0.0.1:8090", backup_node="wss://steem.ws")
```

In this case, Piston will try to connect to a local node first.
If the local node is down, or of a local node goes down at a later time (while Steem instance is in use), it should automatically and quickly fallback to a backup node.

If the main node re-appears, it will be picked up and switched to slowly.

This way, we have 100% uptime guarantee on our long-running Steem instance.
## Benefits
- lower load and bandwidth usage on steem.ws
- automatic redundancy for long-running, critical software, such as internal market-maker or witness price-feeds

**Comment by Netherdrake** [comment]
Could you add this feature to `piston.Steem` as well?

**Comment by xeroc** [comment]
> Could you add this feature to `piston.Steem` as well?

It should have been inherently part of piston.steem.Steem() because it makes use of
this `steemapi`. But I had a bug in `Steem().__init__()` that I just fixed:

```
  #>>> from piston.steem import Steem
  #>>> Steem(node=["wss://localhost:8090", "wss://node.steem.ws"]).rpc.url
  Lost connection to node during wsconnect(): wss://localhost:8090 (1/-1) Retrying in 0 seconds
  'wss://node.steem.ws'
```
